import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import openapiTS, { astToString } from 'openapi-typescript';

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const frontendDirectory = path.resolve(scriptDirectory, '..');
const sourcePath = path.resolve(frontendDirectory, '../backend/dist/openapi.json');
const snapshotPath = path.resolve(scriptDirectory, 'openapi.json');
const generatedPath = path.resolve(frontendDirectory, 'src/lib/api/generated.ts');

const source = JSON.parse(
  await readFile(sourcePath, 'utf8').catch(() => {
    throw new Error(
      `Backend contract not found at ${sourcePath}.\n` +
        'Generate it first: pnpm --prefix backend openapi:generate',
    );
  }),
);
const normalizedContract = `${JSON.stringify(source, null, 2)}\n`;
const ast = await openapiTS(source, { alphabetize: true });
const generated = [
  '/**',
  ' * Generated from backend/dist/openapi.json by `pnpm api:generate`.',
  ' * Do not edit this file by hand.',
  ' */',
  '',
  astToString(ast),
].join('\n');

if (process.argv.includes('--check')) {
  const [committedContract, committedTypes] = await Promise.all([
    readFile(snapshotPath, 'utf8').catch(() => ''),
    readFile(generatedPath, 'utf8').catch(() => ''),
  ]);
  const staleFiles = [
    committedContract === normalizedContract ? undefined : 'openapi/openapi.json',
    committedTypes === generated ? undefined : 'src/lib/api/generated.ts',
  ].filter(Boolean);

  if (staleFiles.length > 0) {
    console.error(`Generated API contract is stale: ${staleFiles.join(', ')}`);
    console.error('Run `pnpm api:generate` and commit the resulting files.');
    process.exitCode = 1;
  } else {
    console.log('Generated API contract is current.');
  }
} else {
  await writeFile(snapshotPath, normalizedContract, 'utf8');
  await writeFile(generatedPath, generated, 'utf8');
}
